((c-mode . ((indent-tabs-mode . nil)
	    (c-file-style . "bsd")
	    (c-basic-offset . 2)
	    (fill-column . 80)))
 (c++-mode . ((indent-tabs-mode . nil)
	      (c-file-style . "bsd")
	      (c-basic-offset . 2)
	      (fill-column . 80))))
